module.exports = {
    // "Wszystkie": [
    //     "001 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w mikroprzedsiębiorstwach bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
    //     "002 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w małych i średnich przedsiębiorstwach (w tym prywatnych organizacjach badawczych) bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
    //     "003 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w dużych przedsiębiorstwach bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
    //     "006 Inwestycje w wartości niematerialne i prawne w MŚP (w tym prywatnych organizacjach badawczych) bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
    //     "009 Działania badawcze i innowacyjne w mikroprzedsiębiorstwach, w tym tworzenie sieci kontaktów (badania przemysłowe, eksperymentalne prace rozwojowe, studia wykonalności)",
    //     "010 Działania badawcze i innowacyjne w MŚP, w tym tworzenie sieci kontaktów",
    //     "011 Działania badawcze i innowacyjne w dużych przedsiębiorstwach, w tym tworzenie sieci kontaktów",
    //     "012 Działania badawcze i innowacyjne w publicznych organizacjach badawczych, instytucjach szkolnictwa wyższego i ośrodkach kompetencji, w tym tworzenie sieci kontaktów (badania przemysłowe, eksperymentalne prace rozwojowe, studia wykonalności)",
    //     "013 Cyfryzacja MŚP (w tym handel elektroniczny, e-biznes i sieciowe procesy biznesowe, ośrodki innowacji cyfrowych, żywe laboratoria, przedsiębiorcy internetowi i przedsiębiorstwa ICT typu start-up, usługi B2B)",
    //     "016 Rozwiązania TIK, usługi elektroniczne, aplikacje dla administracji",
    //     "019 Usługi i aplikacje w zakresie e-zdrowia (w tym e-opieka, internet rzeczy w zakresie aktywności fizycznej i nowoczesnych technologii w służbie osobom starszym)",
    //     "020 Infrastruktura biznesowa dla MŚP (w tym parki i obiekty przemysłowe)",
    //     "021 Rozwój działalności i umiędzynarodowienie MŚP, w tym inwestycje produkcyjne",
    //     "023 Rozwój umiejętności na rzecz inteligentnej specjalizacji, transformacji przemysłowej, przedsiębiorczości i zdolności przedsiębiorstw dostosowania się do zmian",
    //     "024 Zaawansowane usługi wsparcia dla MŚP i grup MŚP (w tym usługi w zakresie zarządzania, marketingu i projektowania)",
    //     "025 Inkubatory przedsiębiorczości, wsparcie dla przedsiębiorstw typu spin-off i spin-out i przedsiębiorstw typu start-up",
    //     "026 Wsparcie dla klastrów innowacyjnych, w tym między przedsiębiorstwami, organizacjami badawczymi i organami publicznymi oraz sieciami biznesowymi, z korzyścią głównie dla MŚP",
    //     "027 Procesy innowacji w MŚP (innowacje w zakresie procesów, organizacji, marketingu, i współtworzenia, innowacje zorientowane na użytkownika i motywowane popytem)",
    //     "028 Transfer technologii i współpraca między przedsiębiorstwami, organizacjami badawczymi i sektorem szkolnictwa wyższego",
    //     "029 Procesy badawcze i innowacyjne, transfer technologii i współpraca między przedsiębiorstwami, organizacjami badawczymi i uczelniami wyższymi, koncentrujące się na gospodarce niskoemisyjnej, odporności i przystosowaniu się do zmian klimatu",
    //     "030 Procesy badawcze i innowacyjne, transfer technologii i współpraca między przedsiębiorstwami koncentrujące się na gospodarce o obiegu zamkniętym",
    //     "034 TIK: sieć szerokopasmowa o bardzo dużej przepustowości (dostęp/lokalna pętla o wydajności równoważnej instalacji światłowodowej do punktu dystrybucji w miejscu świadczenia usługi dla domów i przedsiębiorstw)",
    //     "038 Projekty w zakresie efektywności energetycznej i projekty demonstracyjne w MŚP oraz działania wspierające",
    //     "040 Projekty w zakresie efektywności energetycznej i projekty demonstracyjne w MŚP lub w dużych przedsiębiorstwach oraz działania wspierające zgodne z kryteriami efektywności energetycznej",
    //     "041 Renowacja istniejących budynków mieszkalnych pod kątem efektywności energetycznej, projekty demonstracyjne i działania wspierające",
    //     "042 Renowacja istniejących budynków mieszkalnych pod kątem efektywności energetycznej, projekty demonstracyjne i działania wspierające zgodne z kryteriami efektywności energetycznej",
    //     "044 Renowacja zwiększająca efektywność energetyczną lub działania w zakresie efektywności energetycznej w odniesieniu do infrastruktury publicznej, projekty demonstracyjne i działania wspierające",
    //     "045 Renowacja zwiększająca efektywność energetyczną lub działania w zakresie efektywności energetycznej w odniesieniu do infrastruktury publicznej, projekty demonstracyjne i działania wspierające zgodne z kryteriami efektywności energetycznej",
    //     "046 Wsparcie dla podmiotów, które świadczą usługi wspierające gospodarkę niskoemisyjną i odporność na zmiany klimatu, w tym działania w zakresie zwiększania świadomości",
    //     "047 Energia odnawialna: wiatrowa",
    //     "048 Energia odnawialna: słoneczna",
    //     "050 Energia odnawialna: biomasa o wysokim poziomie redukcji emisji gazów cieplarnianych",
    //     "054 Wysokosprawna kogeneracja, system ciepłowniczy i chłodniczy",
    //     "058 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: powodzie i osunięcia ziemi (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
    //     "059 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: pożary (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
    //     "060 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: inne ryzyka, np. burze i susze (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
    //     "065 Odprowadzanie i oczyszczanie ścieków",
    //     "066 Odprowadzanie i oczyszczanie ścieków zgodne z kryteriami efektywności energetycznej",
    //     "067 Gospodarowanie odpadami z gospodarstw domowych: działania w zakresie zapobiegania powstawaniu odpadów, ich minimalizacji, segregacji, ponownego użycia, recyklingu",
    //     "071 Promowanie wykorzystania materiałów pochodzących z recyklingu jako surowców",
    //     "073 Rewaloryzacja obszarów przemysłowych i rekultywacja skażonych gruntów",
    //     "075 Wsparcie ekologicznych procesów produkcyjnych oraz efektywnego wykorzystywania zasobów w MŚP",
    //     "076 Wsparcie ekologicznych procesów produkcyjnych oraz efektywnego wykorzystywania zasobów w dużych przedsiębiorstwach",
    //     "077 Działania mające na celu poprawę jakości powietrza i ograniczenie hałasu",
    //     "078 Ochrona, regeneracja i zrównoważone wykorzystanie obszarów Natura 2000",
    //     "079 Ochrona przyrody i różnorodności biologicznej, dziedzictwo naturalne i zasoby naturalne, zielona i niebieska infrastruktura",
    //     "081 Infrastruktura czystego transportu miejskiego",
    //     "082 Tabor czystego transportu miejskiego",
    //     "083 Infrastruktura rowerowa",
    //     "087 Nowo wybudowane lub rozbudowane autostrady i drogi – sieć bazowa TEN-T",
    //     "088 Nowo wybudowane lub rozbudowane autostrady i drogi – sieć kompleksowa TEN-T",
    //     "089 Nowo wybudowane lub rozbudowane drugorzędne połączenia drogowe z siecią drogową i węzłami TEN-T",
    //     "090 Nowo wybudowane lub rozbudowane inne krajowe, regionalne i lokalne drogi dojazdowe",
    //     "093 Inne drogi przebudowane lub zmodernizowane (autostrady, drogi krajowe, regionalne lub lokalne)",
    //     "107 Bezemisyjny / zasilany energią elektryczną tabor kolejowy",
    //     "121 Infrastruktura na potrzeby wczesnej edukacji i opieki nad dzieckiem",
    //     "122 Infrastruktura na potrzeby szkolnictwa podstawowego i średniego",
    //     "123 Infrastruktura na potrzeby szkolnictwa wyższego",
    //     "124 Infrastruktura na potrzeby kształcenia i szkolenia zawodowego oraz edukacji dorosłych",
    //     "127 Pozostała infrastruktura społeczna przyczyniająca się do włączenia społecznego",
    //     "128 Infrastruktura zdrowotna",
    //     "129 Wyposażenie opieki zdrowotnej",
    //     "134 Działania na rzecz poprawy dostępu do zatrudnienia",
    //     "136 Wsparcie szczególne na rzecz zatrudnienia ludzi młodych i integracji społeczno-gospodarczej ludzi młodych",
    //     "137 Wsparcie na rzecz samozatrudnienia i zakładania działalności gospodarczej typu start-up",
    //     "138 Wsparcie na rzecz ekonomii społecznej i przedsiębiorstw społecznych",
    //     "139 Działania na rzecz modernizacji i wzmocnienia instytucji i służb rynku pracy celem oceny i przewidywania zapotrzebowania na umiejętności oraz zapewnienia terminowej i dopasowanej do potrzeb pomocy",
    //     "140 Wsparcie na rzecz dostosowania umiejętności i kwalifikacji zawodowych do potrzeb rynku pracy oraz na rzecz przepływów na rynku pracy",
    //     "141 Wsparcie na rzecz mobilności pracowników",
    //     "142 Działania na rzecz promowania aktywności zawodowej kobiet oraz zmniejszenia segregacji na rynku pracy ze względu na płeć",
    //     "143 Działania promujące równowagę między życiem zawodowym a prywatnym obejmujące dostęp do opieki nad dziećmi i osobami niesamodzielnymi",
    //     "145 Wspieranie rozwoju kompetencji cyfrowych",
    //     "146 Wsparcie na rzecz przystosowywania pracowników, przedsiębiorstw i przedsiębiorców do zmian",
    //     "147 Działania zachęcające do aktywnego starzenia się w dobrym zdrowiu",
    //     "148 Wsparcie na rzecz wczesnej edukacji i opieki nad dzieckiem (z wyłączeniem infrastruktury)",
    //     "149 Wsparcie na rzecz szkolnictwa podstawowego i średniego (z wyłączeniem infrastruktury)",
    //     "150 Wsparcie na rzecz szkolnictwa wyższego (z wyłączeniem infrastruktury)",
    //     "151 Wsparcie na rzecz kształcenia dorosłych (z wyłączeniem infrastruktury)",
    //     "152 Działania na rzecz promowania równości szans i aktywnego udziału w życiu społecznym",
    //     "153 Metody integracji z rynkiem pracy oraz powrotu na rynek pracy osób znajdujących się w niekorzystnej sytuacji",
    //     "156 Działania szczególne na rzecz zwiększenia udziału obywateli państw trzecich w rynku pracy",
    //     "157 Działania na rzecz integracji społecznej obywateli państw trzecich",
    //     "158 Działania w celu zwiększenia równego i szybkiego dostępu do dobrej jakości trwałych i przystępnych cenowo usług",
    //     "159 Działania na rzecz poprawy świadczenia usług w zakresie opieki rodzinnej i środowiskowej",
    //     "160 Działania na rzecz poprawy dostępności, efektywności i odporności systemów opieki zdrowotnej (z wyłączeniem infrastruktury)",
    //     "161 Działania na rzecz poprawy dostępu do opieki długoterminowej (z wyłączeniem infrastruktury)",
    //     "163 Promowanie integracji społecznej osób zagrożonych ubóstwem lub wykluczeniem społecznym, w tym osób najbardziej potrzebujących i dzieci",
    //     "165 Ochrona, rozwój i promowanie publicznych walorów turystycznych i usług turystycznych",
    //     "166 Ochrona, rozwój i promowanie dziedzictwa kulturowego i usług w dziedzinie kultury",
    //     "167 Ochrona, rozwój i promowanie dziedzictwa naturalnego i ekoturystyki poza obszarami Natura 2000",
    //     "168 Fizyczna odnowa i bezpieczeństwo przestrzeni publicznych",
    //     "169 Inicjatywy na rzecz rozwoju terytorialnego, w tym przygotowanie strategii terytorialnych",
    //     "170 Zwiększenie zdolności instytucji programu oraz podmiotów związanych z wdrażaniem Funduszy",
    //     "173 Wzmacnianie zdolności instytucjonalnych instytucji publicznych i zainteresowanych stron do wdrażania projektów i inicjatyw w zakresie współpracy terytorialnej w kontekście transgranicznym, transnarodowym, morskim i międzyregionalnym",
    //     "179 Informacja i komunikacja",
    //     "180 Przygotowanie, wdrażanie, monitorowanie i kontrola",
    //     "181 Ewaluacja i badania, gromadzenie danych",
    //     "182 Wzmocnienie potencjału instytucji państwa członkowskiego, beneficjentów i odpowiednich partnerów",
    //     "FBWP-3 FBWP Wspólne zespoły dochodzeniowo-śledcze lub inne wspólne operacje",
    //     "FBWP-4 FBWP Delegowanie lub wysyłanie ekspertów",
    //     "FEDR-11 FEDR Gromadzenie i analiza danych oraz promowanie wiedzy o morzu",
    //     "IZGW-1 IZGW Infrastruktura i budynki",
    //     "IZGW-4 IZGW Systemy łączności"
    // ],
    "Edukacja": [
        "121 Infrastruktura na potrzeby wczesnej edukacji i opieki nad dzieckiem",
        "122 Infrastruktura na potrzeby szkolnictwa podstawowego i średniego",
        "123 Infrastruktura na potrzeby szkolnictwa wyższego",
        "124 Infrastruktura na potrzeby kształcenia i szkolenia zawodowego oraz edukacji dorosłych",
        "148 Wsparcie na rzecz wczesnej edukacji i opieki nad dzieckiem (z wyłączeniem infrastruktury)",
        "149 Wsparcie na rzecz szkolnictwa podstawowego i średniego (z wyłączeniem infrastruktury)",
        "150 Wsparcie na rzecz szkolnictwa wyższego (z wyłączeniem infrastruktury)",
        "151 Wsparcie na rzecz kształcenia dorosłych (z wyłączeniem infrastruktury)"
    ],
    "Energetyka": [
        "038 Projekty w zakresie efektywności energetycznej i projekty demonstracyjne w MŚP oraz działania wspierające",
        "040 Projekty w zakresie efektywności energetycznej i projekty demonstracyjne w MŚP lub w dużych przedsiębiorstwach oraz działania wspierające zgodne z kryteriami efektywności energetycznej",
        "041 Renowacja istniejących budynków mieszkalnych pod kątem efektywności energetycznej, projekty demonstracyjne i działania wspierające",
        "042 Renowacja istniejących budynków mieszkalnych pod kątem efektywności energetycznej, projekty demonstracyjne i działania wspierające zgodne z kryteriami efektywności energetycznej",
        "044 Renowacja zwiększająca efektywność energetyczną lub działania w zakresie efektywności energetycznej w odniesieniu do infrastruktury publicznej, projekty demonstracyjne i działania wspierające",
        "045 Renowacja zwiększająca efektywność energetyczną lub działania w zakresie efektywności energetycznej w odniesieniu do infrastruktury publicznej, projekty demonstracyjne i działania wspierające zgodne z kryteriami efektywności energetycznej",
        "046 Wsparcie dla podmiotów, które świadczą usługi wspierające gospodarkę niskoemisyjną i odporność na zmiany klimatu, w tym działania w zakresie zwiększania świadomości",
        "047 Energia odnawialna: wiatrowa",
        "048 Energia odnawialna: słoneczna",
        "050 Energia odnawialna: biomasa o wysokim poziomie redukcji emisji gazów cieplarnianych",
        "054 Wysokosprawna kogeneracja, system ciepłowniczy i chłodniczy"
    ],
    "Badania i Innowacje": [
        "001 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w mikroprzedsiębiorstwach bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
        "002 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w małych i średnich przedsiębiorstwach (w tym prywatnych organizacjach badawczych) bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
        "003 Inwestycje w środki trwałe, w tym infrastrukturę badawczą, w dużych przedsiębiorstwach bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
        "006 Inwestycje w wartości niematerialne i prawne w MŚP (w tym prywatnych organizacjach badawczych) bezpośrednio związane z działaniami badawczymi i innowacyjnymi",
        "009 Działania badawcze i innowacyjne w mikroprzedsiębiorstwach, w tym tworzenie sieci kontaktów (badania przemysłowe, eksperymentalne prace rozwojowe, studia wykonalności)",
        "010 Działania badawcze i innowacyjne w MŚP, w tym tworzenie sieci kontaktów",
        "011 Działania badawcze i innowacyjne w dużych przedsiębiorstwach, w tym tworzenie sieci kontaktów",
        "012 Działania badawcze i innowacyjne w publicznych organizacjach badawczych, instytucjach szkolnictwa wyższego i ośrodkach kompetencji, w tym tworzenie sieci kontaktów (badania przemysłowe, eksperymentalne prace rozwojowe, studia wykonalności)",
        "013 Cyfryzacja MŚP (w tym handel elektroniczny, e-biznes i sieciowe procesy biznesowe, ośrodki innowacji cyfrowych, żywe laboratoria, przedsiębiorcy internetowi i przedsiębiorstwa ICT typu start-up, usługi B2B)",
        "016 Rozwiązania TIK, usługi elektroniczne, aplikacje dla administracji",
        "019 Usługi i aplikacje w zakresie e-zdrowia (w tym e-opieka, internet rzeczy w zakresie aktywności fizycznej i nowoczesnych technologii w służbie osobom starszym)",
        "020 Infrastruktura biznesowa dla MŚP (w tym parki i obiekty przemysłowe)",
        "021 Rozwój działalności i umiędzynarodowienie MŚP, w tym inwestycje produkcyjne",
        "023 Rozwój umiejętności na rzecz inteligentnej specjalizacji, transformacji przemysłowej, przedsiębiorczości i zdolności przedsiębiorstw dostosowania się do zmian",
        "024 Zaawansowane usługi wsparcia dla MŚP i grup MŚP (w tym usługi w zakresie zarządzania, marketingu i projektowania)",
        "025 Inkubatory przedsiębiorczości, wsparcie dla przedsiębiorstw typu spin-off i spin-out i przedsiębiorstw typu start-up",
        "026 Wsparcie dla klastrów innowacyjnych, w tym między przedsiębiorstwami, organizacjami badawczymi i organami publicznymi oraz sieciami biznesowymi, z korzyścią głównie dla MŚP",
        "027 Procesy innowacji w MŚP (innowacje w zakresie procesów, organizacji, marketingu, i współtworzenia, innowacje zorientowane na użytkownika i motywowane popytem)",
        "028 Transfer technologii i współpraca między przedsiębiorstwami, organizacjami badawczymi i sektorem szkolnictwa wyższego",
        "029 Procesy badawcze i innowacyjne, transfer technologii i współpraca między przedsiębiorstwami, organizacjami badawczymi i uczelniami wyższymi, koncentrujące się na gospodarce niskoemisyjnej, odporności i przystosowaniu się do zmian klimatu",
        "030 Procesy badawcze i innowacyjne, transfer technologii i współpraca między przedsiębiorstwami koncentrujące się na gospodarce o obiegu zamkniętym"
    ],
    "Zdrowie": [
        "128 Infrastruktura zdrowotna",
        "129 Wyposażenie opieki zdrowotnej",
        "019 Usługi i aplikacje w zakresie e-zdrowia (w tym e-opieka, internet rzeczy w zakresie aktywności fizycznej i nowoczesnych technologii w służbie osobom starszym)",
        "160 Działania na rzecz poprawy dostępności, efektywności i odporności systemów opieki zdrowotnej (z wyłączeniem infrastruktury)",
        "161 Działania na rzecz poprawy dostępu do opieki długoterminowej (z wyłączeniem infrastruktury)"
    ],
    "Transport": [
        "081 Infrastruktura czystego transportu miejskiego",
        "082 Tabor czystego transportu miejskiego",
        "083 Infrastruktura rowerowa",
        "087 Nowo wybudowane lub rozbudowane autostrady i drogi – sieć bazowa TEN-T",
        "088 Nowo wybudowane lub rozbudowane autostrady i drogi – sieć kompleksowa TEN-T",
        "089 Nowo wybudowane lub rozbudowane drugorzędne połączenia drogowe z siecią drogową i węzłami TEN-T",
        "090 Nowo wybudowane lub rozbudowane inne krajowe, regionalne i lokalne drogi dojazdowe",
        "093 Inne drogi przebudowane lub zmodernizowane (autostrady, drogi krajowe, regionalne lub lokalne)",
        "107 Bezemisyjny / zasilany energią elektryczną tabor kolejowy"
    ],
    "Społeczeństwo": [
        "127 Pozostała infrastruktura społeczna przyczyniająca się do włączenia społecznego",
        "134 Działania na rzecz poprawy dostępu do zatrudnienia",
        "136 Wsparcie szczególne na rzecz zatrudnienia ludzi młodych i integracji społeczno-gospodarczej ludzi młodych",
        "137 Wsparcie na rzecz samozatrudnienia i zakładania działalności gospodarczej typu start-up",
        "138 Wsparcie na rzecz ekonomii społecznej i przedsiębiorstw społecznych",
        "139 Działania na rzecz modernizacji i wzmocnienia instytucji i służb rynku pracy celem oceny i przewidywania zapotrzebowania na umiejętności oraz zapewnienia terminowej i dopasowanej do potrzeb pomocy",
        "140 Wsparcie na rzecz dostosowania umiejętności i kwalifikacji zawodowych do potrzeb rynku pracy oraz na rzecz przepływów na rynku pracy",
        "141 Wsparcie na rzecz mobilności pracowników",
        "142 Działania na rzecz promowania aktywności zawodowej kobiet oraz zmniejszenia segregacji na rynku pracy ze względu na płeć",
        "143 Działania promujące równowagę między życiem zawodowym a prywatnym obejmujące dostęp do opieki nad dziećmi i osobami niesamodzielnymi",
        "145 Wspieranie rozwoju kompetencji cyfrowych",
        "146 Wsparcie na rzecz przystosowywania pracowników, przedsiębiorstw i przedsiębiorców do zmian",
        "147 Działania zachęcające do aktywnego starzenia się w dobrym zdrowiu",
        "152 Działania na rzecz promowania równości szans i aktywnego udziału w życiu społecznym",
        "153 Metody integracji z rynkiem pracy oraz powrotu na rynek pracy osób znajdujących się w niekorzystnej sytuacji",
        "156 Działania szczególne na rzecz zwiększenia udziału obywateli państw trzecich w rynku pracy",
        "157 Działania na rzecz integracji społecznej obywateli państw trzecich",
        "158 Działania w celu zwiększenia równego i szybkiego dostępu do dobrej jakości trwałych i przystępnych cenowo usług",
        "159 Działania na rzecz poprawy świadczenia usług w zakresie opieki rodzinnej i środowiskowej",
        "163 Promowanie integracji społecznej osób zagrożonych ubóstwem lub wykluczeniem społecznym, w tym osób najbardziej potrzebujących i dzieci"
    ],
    "Środowisko": [
        "058 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: powodzie i osunięcia ziemi (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
        "059 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: pożary (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
        "060 Działania w zakresie przystosowania się do zmian klimatu oraz zapobieganie ryzykom związanym z klimatem i zarządzanie nimi: inne ryzyka, np. burze i susze (w tym zwiększanie świadomości, ochrona ludności i systemy zarządzania klęskami żywiołowymi i katastrofami, infrastruktura i podejście ekosystemowe)",
        "065 Odprowadzanie i oczyszczanie ścieków",
        "066 Odprowadzanie i oczyszczanie ścieków zgodne z kryteriami efektywności energetycznej",
        "067 Gospodarowanie odpadami z gospodarstw domowych: działania w zakresie zapobiegania powstawaniu odpadów, ich minimalizacji, segregacji, ponownego użycia, recyklingu",
        "071 Promowanie wykorzystania materiałów pochodzących z recyklingu jako surowców",
        "073 Rewaloryzacja obszarów przemysłowych i rekultywacja skażonych gruntów",
        "075 Wsparcie ekologicznych procesów produkcyjnych oraz efektywnego wykorzystywania zasobów w MŚP",
        "076 Wsparcie ekologicznych procesów produkcyjnych oraz efektywnego wykorzystywania zasobów w dużych przedsiębiorstwach",
        "077 Działania mające na celu poprawę jakości powietrza i ograniczenie hałasu",
        "078 Ochrona, regeneracja i zrównoważone wykorzystanie obszarów Natura 2000",
        "079 Ochrona przyrody i różnorodności biologicznej, dziedzictwo naturalne i zasoby naturalne, zielona i niebieska infrastruktura"
    ],
    "Kultura i Turystyka": [
        "165 Ochrona, rozwój i promowanie publicznych walorów turystycznych i usług turystycznych",
        "166 Ochrona, rozwój i promowanie dziedzictwa kulturowego i usług w dziedzinie kultury",
        "167 Ochrona, rozwój i promowanie dziedzictwa naturalnego i ekoturystyki poza obszarami Natura 2000",
        "168 Fizyczna odnowa i bezpieczeństwo przestrzeni publicznych"
    ],
    "Administracja": [
        "169 Inicjatywy na rzecz rozwoju terytorialnego, w tym przygotowanie strategii terytorialnych",
        "170 Zwiększenie zdolności instytucji programu oraz podmiotów związanych z wdrażaniem Funduszy",
        "173 Wzmacnianie zdolności instytucjonalnych instytucji publicznych i zainteresowanych stron do wdrażania projektów i inicjatyw w zakresie współpracy terytorialnej w kontekście transgranicznym, transnarodowym, morskim i międzyregionalnym",
        "179 Informacja i komunikacja",
        "180 Przygotowanie, wdrażanie, monitorowanie i kontrola",
        "181 Ewaluacja i badania, gromadzenie danych",
        "182 Wzmocnienie potencjału instytucji państwa członkowskiego, beneficjentów i odpowiednich partnerów"
    ],
    "Bezpieczeństwo": [
        "FBWP-3 FBWP Wspólne zespoły dochodzeniowo-śledcze lub inne wspólne operacje",
        "FBWP-4 FBWP Delegowanie lub wysyłanie ekspertów"
    ],
    "Gospodarka Morska": [
        "FEDR-11 FEDR Gromadzenie i analiza danych oraz promowanie wiedzy o morzu"
    ],
    "Łączność i Infrastruktura": [
        "IZGW-1 IZGW Infrastruktura i budynki",
        "IZGW-4 IZGW Systemy łączności",
        "034 TIK: sieć szerokopasmowa o bardzo dużej przepustowości (dostęp/lokalna pętla o wydajności równoważnej instalacji światłowodowej do punktu dystrybucji w miejscu świadczenia usługi dla domów i przedsiębiorstw)"
    ]
};

const wojewodztwa = [
    "DOLNOŚLĄSKIE", "KUJAWSKO-POMORSKIE", "LUBELSKIE", "LUBUSKIE",
    "ŁÓDZKIE", "MAŁOPOLSKIE", "MAZOWIECKIE", "OPOLSKIE",
    "PODKARPACKIE", "PODLASKIE", "POMORSKIE", "ŚLĄSKIE",
    "ŚWIĘTOKRZYSKIE", "WARMIŃSKO-MAZURSKIE", "WIELKOPOLSKIE", "ZACHODNIOPOMORSKIE"
];
